
CREATE DATABASE catalogo;

DROP TABLE IF EXISTS `PERSONAJES`;

CREATE TABLE `PERSONAJES`(
`PERS_CLAVE`  int(5) unsigned NOT NULL AUTO_INCREMENT,
`PERS_NOMBRE` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
`PERS_EMPRESA` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
PRIMARY KEY(`PERS_CLAVE`)
)ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;